name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Install Robot Framework and SeleniumLibrary
        run: pip install --upgrade robotframework-seleniumlibrary

      - name: Install Firefox browser
        run: sudo apt-get install -y firefox
     
      - name: Install GeckoDriver
        run: |
          GECKODRIVER_VERSION=$(curl -sS https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
          wget https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz
          tar -xzf geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver

      - name: Install webdriver_manager
        run: pip install --upgrade webdriver_manager
        
      - name: Install Selenium
        run: pip install selenium==4.9.1

      - name: Set up Firefox environment variables
        run: |
          echo "MOZ_HEADLESS=1" >> $GITHUB_ENV

      - name: Delete existing geckodriver logs
        run: |
          rm -f robot_automation/logs/geckodriver*.log

      - name: Run Robot Framework tests
        run: |
          robot --outputdir robot_automation/logs --log robot_automation/logs/log.html robot_automation/robot_basics
          if [ $? -eq 0 ]; then  # Check the exit code of the previous command
            echo -e "\e[32mTests passed!\e[0m"  # Set text color to green for pass
          else
            echo -e "\e[31mTests failed!\e[0m"  # Set text color to red for fail
          fi

      - name: Display Robot Framework logs
        run: |
          echo -e "\nTest Results:\n"
          cat robot_automation/logs/log.html | awk -v RS='</tr>' -F '</td>' '{
            if (match($0, "<td class=\"fail\">")) {
              printf "\e[31m%s\e[0m\n", $2
            } else if (match($0, "<td class=\"pass\">")) {
              printf "\e[32m%s\e[0m\n", $2
            }
          }'
          
      - name: Commit and push logs
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add robot_automation/logs
          git commit -m "Add Robot Framework logs"
          git push
